dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.home, name = 'home')
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('contact/',views.contact, name='contact'),
    path('about/',views.about, name='about'),
    path('testimonials/',views.testimonials, name='testimonials'),
    path('login/',auth_views.LoginView.as_view(template_name = 'login.html'), name='login'),
    path('logout',auth_views.LogoutView.as_view(), name = 'logout' ),
    path('dashboard/', include('dashboard.urls')),
    path('smartphone/', include('smartphone.urls')),
]

smartphone/urls.py
from django.urls import path
from . import views

app_name = 'smartphone'

urlpatterns = [
    path('',views.home, name = 'home')
    ]

dashboard/models.py
from django.db import models

# Create your models here.

smartphone/models.py
from django.db import models


class Smartphone(models.Model):
    model = models.CharField(max_length=50)

    class Meta:
        permissions = [
            ("can_publish", "Can publish smartphones"),
            ("can_view_details", "Can view detailed smartphone information"),
        ]

    def __str__(self):
        return f"{self.model}"

mysite/forms.py
from django import forms

class ContactForm(forms.Form):
   #  COUNTRIES = [
   #     ('CL', 'Chile'),
   #     ('VE', 'Venezuela'),
   #     ('AR', 'Argentina'),
   #     ('US', 'E.E.U.U')
   #     ]
   # # Agregar los campos del formulario
   #  name = forms.CharField(label='Nombre', max_length=400)
   #  email = forms.EmailField()
   #  age = forms.IntegerField(min_value=1)
   #  country = forms.ChoiceField(choices=COUNTRIES)
   #  country_extra = forms.MultipleChoiceField(choices=COUNTRIES)
   email = forms.EmailField(
       widget=forms.TextInput(attrs={
           'class':'form-control',
           'placeholder': 'example@gmail.com'
           })
       )
   comment = forms.CharField(
       widget=forms.Textarea(attrs={
           'class':'form-control',
           'rows': 3           
           })
       )
   firstName = forms.CharField(
       widget=forms.TextInput(attrs={
           'class':'form-control',
           'placeholder': 'First Name'
           })
       )

   lastName = forms.CharField(
       widget=forms.TextInput(attrs={
           'class':'form-control',
           'placeholder': 'Last Name'
           })
       )

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required()
def home(request):
    return render(request, 'dashboard/home.html')

mysite/views.py
from mysite.forms import ContactForm

from django.http import HttpResponse
from django.shortcuts import render
import datetime

def home(request):
    # first_name='Sergio'
    # last_name=' Henriquez'
    # context={'first_name':first_name, 'last_name':last_name}
    # return render(request, 'home.html', context)
    return render(request, 'home.html')

def contact (request):
    # # now=datetime.datetime.now
    # # return render(request, 'contact.html', context={'date_now': now})
    # if request.method == 'POST':
    #    form = ContactForm(request.POST)
    #    print ('***' ,request.method)
    #    print(request.POST)

    # else:

    #     form = ContactForm()
     
    
    
    # return render(request,  'contact.html', context={'form':form})
     return render(request,  'contact.html')

def about (request):
     return render(request, 'about.html')

def testimonials(request):
    testimonials=[
         {
             'name':'Maria',
             'testimonial':'Exelente servicio'
         },
         {
             'name':'Juan',
             'testimonial':'No me gusto la pagina'
         }]
    return render(request, 'testimonials.html', context={'data':testimonials})

smartphone/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required


# Create your views here.

@permission_required('smartphone.view_smartphone', raise_exception=True)
def home(request):
    return render(request, 'smartphone/home.html')

dashboard/templates/dashboard/home.html
{% extends "general/base.html" %}

{%block title%} Dashboard - Home {%endblock%}

{% block content %}
<h1>Dashboard</h1>

    {% if request.user.is_authenticated %}
<form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">Salir</button>
</form>
    {% endif %}
{% endblock %}


<!--<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Dashboar::Home</title>
</head>
<body>
    <h1>Dashboard</h1>
    {% if request.user.is_authenticated %}-->
<!-- <a href="{% url 'logout' %}">Salir</a>-->
<!--<form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Salir</button>
    </form>
    {% endif %}
</body>
</html>-->

mysite/dashboard/templates/dashboard/home.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Dashboar::Home</title>
</head>
<body>
    <h1>Dashboard</h1>
    {% if request.user.is_authenticated %}
   <!-- <a href="{% url 'logout' %}">Salir</a>-->
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Salir</button>
    </form>
    {% endif %}
</body>
</html>

smartphone/templates/smartphone/home.html
{% extends "general/base.html" %}

{%block title%} Smartphone - Home {%endblock%}

{% block content %}
<h1>Smartphone</h1>

   
{% endblock %}


<!--<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Dashboar::Home</title>
</head>
<body>
    <h1>Dashboard</h1>
    {% if request.user.is_authenticated %}-->
<!-- <a href="{% url 'logout' %}">Salir</a>-->
<!--<form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Salir</button>
    </form>
    {% endif %}
</body>
</html>-->

templates/about.html
{% extends "base.html" %}

{%block title %} About {%endblock%}

{% block content %}

<h1>About</h1>
{% endblock %}





<!--<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>About</title>
</head>
<body>
    <h1>About {% now "d/m/Y"%} </h1>
</body>
</html>-->

templates/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>{%block title%} Mysite {%endblock%}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <!--  <a class="navbar-brand" href="#">Navbar</a>-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    <!--<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
    </li>-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Register</a>
                    </li>
                </ul>
                
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script>src = "{% static 'js/bootstrap/bootstrap.js' %}"</script>
</body>
</html>

templates/contact.html
{% extends "base.html" %}

{%block title %} Contact {%endblock%}

{% block content %}
<h1>Contact</h1>
<!--<div class="container">
    <div class="row">
        <div class="col">
            <h1>Contact {{ date_now|date:"d/m/y" }}</h1>
            <form method="post">
                {% csrf_token %}-->
                <!-- <table>-->
                <!--{{ form.as_table}}-->
                <!--</table>-->

                <!--<div class="mb-3">
                    <label for="{{form.email.id_for_label}}" class="form-label">Email Address</label>
                    {{form.email}}
                </div>
                <div class="mb-3">
                    <label for="{{form.comment.id_for_label}}" class="form-label">Comment</label>
                    {{form.comment}}
                </div>

                <button type="submit">EnviarContacto</button>
            </form>
            <div class="row">
                <div class="col">
                    {{form.firstName}}
                </div>
                <div class="col">

                    {{form.lastName}}
                </div>
            </div>
        </div>
    </div>
</div>-->
{% endblock %}

templates/general/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>{%block title%} Mysite {%endblock%}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
<div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">CheckApp</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a href="{% url 'dashboard:home' %}" class="nav-link align-middle px-0">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span>
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'smartphone:home' %}" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">SmartPhones</span></a>
                        </li>

                    </ul>
                </div>
            </div>
            <div class="col py-3">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
    <script>src = "{% static 'js/bootstrap/bootstrap.js' %}"</script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{%block title %} Home {%endblock%}

{% block content %}
<!--<h1>Welcome, {{first_name|upper}} {{last_name|lower}} {{first_name|title}}</h1>-->
<h1>Welcome, </h1>
   
{% endblock %}

templates/login.html
{% extends "base.html" %}

{%block title %} Login {%endblock%}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">Ingresar</button>
</form>
{% endblock %}

templates/testimonials.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Testimonials</title>
</head>
<body>
    <h1>Testimonials</h1>
    {%for persona in data %}
    <p>{{persona.name}} - {{persona.testimonial}}</p>
    {%endfor %}
</body>
</html>